name: Merge upstream into main
on: 
  schedule:
    - cron: '0 0 * * *' # Run every day at midnight
jobs:
  merge-from-upstream-repo:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main # set the branch to merge to
          fetch-depth: 0 # get all changes
      - name: Merge from upstream repo
        uses: discdiver/merge-from-upstream-repo@v0.0.9
        with:
          useremail: harlan@harlanlewis.com # set the user email for git commits
          username: harlanlewis # set the user name for git commits
          upstream: enricoros/big-agi # set the upstream repo
          upstream-branch: main # set the upstream branch to merge from
          branch: main # set the branch to merge to
